if has("gui_macvim")
    macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>
    macmenu File.New\ Tab key=<D-T>
    map <D-t> :CommandTFlush<cr>\|:CommandT<cr>
    imap <D-t> <Esc>:CommandTFlush<cr>\|:CommandT<cr>

endif
map <D-F> :Ack!<space>
imap <D-F> <Esc>:Ack!<space>
map <D-/> <plug>NERDCommenterToggle<CR>j
imap <D-/> <Esc><plug>NERDCommenterToggle<CR>i

" Command-][ to increase/decrease indentation
vmap <D-]> >gv
vmap <D-[> <gv
map <Leader>= <C-w>=
imap <Leader>= <Esc> <C-w>=

