if has("gui_macvim")
  set guifont=Roboto\ Mono:h14
  set guifont=Source\ Code\ Pro:h14
  set guifont=Inconsolata-G:h14
  " set linespace=0
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>
  macmenu File.New\ Tab key=<D-T>
  macmenu Edit.Select\ All key=<nop>
  map <D-t> :CtrlP<cr>
  imap <D-t> <Esc>:CtrlP<cr>
  map <D-F> :Ack!<space>
  imap <D-F> <Esc>:Ack!<space>
  map <D-a> <C-a>
  imap <D-a> <C-a>

  " Command-][ to increase/decrease indentation
  vmap <D-]> >gv
  vmap <D-[> <gv

  " set bg=dark
  set guioptions-=L
  set guioptions-=r
  set guioptions-=T
  set showtabline=1
  let g:hybrid_reduced_contrast=1
  " hi Search         guifg=NONE        guibg=NONE        gui=underline ctermfg=NONE        ctermbg=NONE        cterm=underline
  colors base16-materia
endif

" " Retina Macbook screen doesn't display Roboto Mono as nicely as the 4k monitor
" if hostname() =~ "macbook-pro"
"   set guifont=Source\ Code\ Pro:h14
"   set linespace=1
"   " colors grb256
" endif


" Shortcuts to switch fonts
function! Font1()
  set guifont=Roboto\ Mono:h12
  set linespace=1
endfunction

function! Font2()
  set guifont=Inconsolata-G:h14
  set linespace=0
endfunction

function! Font3()
  set guifont=Source\ Code\ Pro:h14
  set linespace=2
endfunction

function! Font4()
  set guifont=Roboto\ Mono:h13
  set linespace=2
endfunction

map <leader>f1 :call Font1()<cr>
map <leader>f2 :call Font2()<cr>
map <leader>f3 :call Font3()<cr>
map <leader>f4 :call Font4()<cr>
